apiVersion: v1
kind: Service
metadata:
  labels:
    app: aws-spot-controller
  name: aws-spot-controller
  namespace: root-supervisor
spec:
  ports:
    - port: 50051
      protocol: TCP
  selector:
    plugin_name: aws-spot-controller
  sessionAffinity: None
  type: ClusterIP