apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-spot-controller
  labels:
    service_type: spot_automation.Controller
    domain_id: domain-c5eda5293fd5
    plugin_name: aws-spot-controller
    supervisor_name: root
    version: "1.0"
  namespace: spaceone
spec:
  replicas: 1
  selector:
    matchLabels:
      service_type: spot_automation.Controller
      domain_id: domain-c5eda5293fd5
      plugin_name: aws-spot-controller
      supervisor_name: root
      version: "1.0"
  template:
    metadata:
      labels:
        service_type: spot_automation.Controller
        domain_id: domain-c5eda5293fd5
        plugin_name: aws-spot-controller
        supervisor_name: root
        version: "1.0"
    spec:
      containers:
      - name: aws-spot-controller
        image: 728099990403.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone-dev/aws-spot-controller:latest
        ports:
        - containerPort: 50051
          protocol: TCP
        imagePullPolicy: Always
      nodeSelector:
        node.kubernetes.io/lifecycle: spot
